### PR TITLE
Peggy

### PR DESCRIPTION
**Pull request by renfelo**
@adammeghji (cc: @nsendhavdq) This is the branch that adds all pending features from official package.

## FYI
* Merging any branches on main will make it hard to fix any conflicts that probably will appear on future, so feel free to change it here and then just correct all conflicts as soon as possible.

## Changes

- [x] Fix issue with max resolution capture: https://linear.app/peggy/issue/PEG-822/camera-capture-isnt-on-the-maximum-resolution

### CODE REVIEW

**Comment by renfelo** [comment]
@adammeghji our main branch was not been updated for a while (63 commits behind the official package). Can you please fetch these changes? I'll merge here next.

**Comment by adammeghji** [comment]
@renfelo done!

**Comment by adammeghji** [comment]
@renfelo oops I closed this by accident, did you still need this?

**Comment by renfelo** [comment]
We're using this branch inside app in order to keep the master clean, but I'm happy to stick with master if you find it better.

**Pull request closed without merging**
